spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_HOST}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    com.github.kellyihyeon.stanceadmin: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace  # 파라미터 값 출력